function eventCalendar = pushEventToCalendar(eventCalendar, newEvent)
    % PUSHEVENTTOCALENDAR Adds one event to the event calendar.

    assert(isfield(newEvent, "time") && isscalar(newEvent.time) && isfinite(newEvent.time), ...
    "Invalid event pushed: time must be finite scalar.");

    assert(isfield(newEvent, "type") && ...
           ((isstring(newEvent.type) && isscalar(newEvent.type) && strlength(newEvent.type) > 0) || ...
            (ischar(newEvent.type) && ~isempty(newEvent.type))), ...
        "Invalid event pushed: type must be nonempty scalar string or char.");
    
    assert(isfield(newEvent, "aircraftID") && isscalar(newEvent.aircraftID) && ...
           isfinite(newEvent.aircraftID) && newEvent.aircraftID > 0, ...
        "Invalid event pushed: aircraftID must be positive finite scalar.");

    assert(isfield(newEvent, "serverID") && isscalar(newEvent.serverID) && ...
           (isnan(newEvent.serverID) || (isfinite(newEvent.serverID) && newEvent.serverID > 0)), ...
        "Invalid event pushed: serverID must be NaN or positive finite scalar.");
        assert(isfield(newEvent, "time") && isscalar(newEvent.time) && isfinite(newEvent.time), ...
        "Invalid event pushed: time must be finite scalar.");

    assert(isfield(newEvent, "type") && isstring(newEvent.type) && isscalar(newEvent.type) && strlength(newEvent.type) > 0, ...
        "Invalid event pushed: type must be nonempty scalar string.");
    
    assert(isfield(newEvent, "aircraftID") && isscalar(newEvent.aircraftID) && isfinite(newEvent.aircraftID) && newEvent.aircraftID > 0, ...
        "Invalid event pushed: aircraftID must be positive finite scalar.");
    
    assert(isfield(newEvent, "serverID") && isscalar(newEvent.serverID), ...
        "Invalid event pushed: serverID must be scalar.");

    eventCalendar.events(end + 1, 1) = newEvent;
    eventCalendar.isSorted = false;
end