% function grids = buildGridsForCAPEXSweep()
%     % BUILDGRIDSFORCAPEXSWEEP Defines deterministic CAPEX sensitivity grids.
%     %
%     % The CAPEX model is:
%     %
%     %   I(k,e) = C0 + Ck*k + Ce*k*max(e - e0, 0)^p
%     %
%     % where:
%     %   C0 = fixed infrastructure/design/permitting cost
%     %   Ck = per-server capital cost
%     %   Ce = per-server service-rate upgrade cost
%     %   e0 = baseline service rate
%     %   p  = curvature on service-rate upgrades
%     %
%     % Output:
%     %   grids - struct containing all CAPEX sweep grid values.
% 
%     grids = struct();
% 
%     % Match/cover the DES policy space. Include extra values so the CAPEX
%     % table remains usable if later DES runs extend the policy grid.
%     grids.policyKValues = (3:12).';
%     grids.policyEValues = (1.0:0.25:4.0).';
% 
%     % Baseline service-rate level. Service-rate upgrade CAPEX is charged only
%     % above this value.
%     grids.baselineServiceRate = min(grids.policyEValues);
% 
%     % Broad financial assumptions.
%     grids.discountRateValues = [ ...
%         0.00; ...
%         0.02; ...
%         0.04; ...
%         0.06; ...
%         0.08; ...
%         0.10; ...
%         0.12; ...
%         0.15];
% 
%     grids.assetLifeValues = [ ...
%          5; ...
%          7; ...
%         10; ...
%         12; ...
%         15; ...
%         20; ...
%         25; ...
%         30];
% 
%     % Fixed project/infrastructure cost.
%     grids.fixedInfrastructureCostValues = [ ...
%               0; ...
%         2500000; ...
%         5000000; ...
%        10000000; ...
%        20000000; ...
%        40000000];
% 
%     % Per-server capital cost.
%     grids.serverCapitalCostValues = [ ...
%          500000; ...
%         1000000; ...
%         2000000; ...
%         4000000; ...
%         8000000; ...
%        12000000];
% 
%     % Cost of making each server faster/more capable.
%     grids.serviceRateUpgradeCostValues = [ ...
%               0; ...
%          250000; ...
%          500000; ...
%         1000000; ...
%         2000000; ...
%         4000000; ...
%         8000000];
% 
%     % Curvature captures whether faster service becomes increasingly costly.
%     % p = 1.00: linear upgrade cost
%     % p > 1.00: convex upgrade cost
%     grids.serviceRateCurvatureValues = [ ...
%         1.00; ...
%         1.25; ...
%         1.50; ...
%         2.00; ...
%         2.50];
% 
%     grids.outputDirectory = "results";
% 
%     validateCAPEXGrids(grids);
% end
% 


function grids = buildGridsForCAPEXSweep()
    % BUILDGRIDSFORCAPEXSWEEP Defines a broad but file-size-controlled CAPEX grid.

    grids = struct();

    % Match likely DES policy grid plus modest extension.
    grids.policyKValues = (4:10).';
    grids.policyEValues = [1.0; 1.5; 2.0; 2.5; 3.0; 3.5];

    grids.baselineServiceRate = min(grids.policyEValues);

    % Financial assumptions: enough sensitivity, not combinatorial insanity.
    grids.discountRateValues = [0.04; 0.07; 0.10; 0.13];
    grids.assetLifeValues = [10; 15; 20; 25];

    % Capital model assumptions.
    grids.fixedInfrastructureCostValues = [0; 5000000; 15000000; 30000000];

    grids.serverCapitalCostValues = [ ...
        1000000; ...
        3000000; ...
        6000000; ...
        10000000];

    grids.serviceRateUpgradeCostValues = [ ...
        0; ...
        500000; ...
        1500000; ...
        4000000];

    % Keep only linear, moderately convex, strongly convex.
    grids.serviceRateCurvatureValues = [1.0; 1.5; 2.0];

    grids.outputDirectory = getProjectOutputDirectory();

    validateCAPEXGrids(grids);
end

function outputDirectory = getProjectOutputDirectory()
    % GETPROJECTOUTPUTDIRECTORY Returns outputs folder in project root.
    %
    % Robust to nested src folders and avoids string/char issues.

    currentFilePath = mfilename('fullpath');
    currentDirectory = fileparts(currentFilePath);

    % Normalize to char (defensive)
    currentDirectory = char(currentDirectory);

    % Look for '/src' or '\src' depending on OS
    srcToken = [filesep, 'src'];

    srcIndex = strfind(currentDirectory, srcToken);

    assert(~isempty(srcIndex), ...
        'getProjectOutputDirectory:CannotFindSrcFolder', ...
        'Could not infer project root because path does not contain a src folder.');

    % Take everything BEFORE the last '/src'
    projectRoot = currentDirectory(1 : srcIndex(end) - 1);

    outputDirectory = fullfile(projectRoot, 'outputs');
end

function validateCAPEXGrids(grids)
    % VALIDATECAPEXGRIDS Enforces basic validity of CAPEX sweep grids.

    requiredFields = [ ...
        "policyKValues", ...
        "policyEValues", ...
        "baselineServiceRate", ...
        "discountRateValues", ...
        "assetLifeValues", ...
        "fixedInfrastructureCostValues", ...
        "serverCapitalCostValues", ...
        "serviceRateUpgradeCostValues", ...
        "serviceRateCurvatureValues", ...
        "outputDirectory"];

    for iField = 1:numel(requiredFields)
        fieldName = requiredFields(iField);
        assert(isfield(grids, fieldName), ...
            "validateCAPEXGrids:MissingField", ...
            "Missing required field grids.%s.", fieldName);
    end

    assert(all(grids.policyKValues > 0), ...
        "validateCAPEXGrids:InvalidPolicyK", ...
        "All policyKValues must be positive.");

    assert(all(mod(grids.policyKValues, 1) == 0), ...
        "validateCAPEXGrids:NonIntegerPolicyK", ...
        "All policyKValues must be integers.");

    assert(all(grids.policyEValues > 0), ...
        "validateCAPEXGrids:InvalidPolicyE", ...
        "All policyEValues must be positive.");

    assert(isscalar(grids.baselineServiceRate) && grids.baselineServiceRate > 0, ...
        "validateCAPEXGrids:InvalidBaselineServiceRate", ...
        "baselineServiceRate must be a positive scalar.");

    assert(all(grids.discountRateValues >= 0), ...
        "validateCAPEXGrids:InvalidDiscountRate", ...
        "All discountRateValues must be nonnegative.");

    assert(all(grids.assetLifeValues > 0), ...
        "validateCAPEXGrids:InvalidAssetLife", ...
        "All assetLifeValues must be positive.");

    assert(all(grids.fixedInfrastructureCostValues >= 0), ...
        "validateCAPEXGrids:InvalidFixedCost", ...
        "All fixedInfrastructureCostValues must be nonnegative.");

    assert(all(grids.serverCapitalCostValues >= 0), ...
        "validateCAPEXGrids:InvalidServerCost", ...
        "All serverCapitalCostValues must be nonnegative.");

    assert(all(grids.serviceRateUpgradeCostValues >= 0), ...
        "validateCAPEXGrids:InvalidServiceUpgradeCost", ...
        "All serviceRateUpgradeCostValues must be nonnegative.");

    assert(all(grids.serviceRateCurvatureValues > 0), ...
        "validateCAPEXGrids:InvalidCurvature", ...
        "All serviceRateCurvatureValues must be positive.");
end