function outputFilePath = writeCAPEXResultsToCSV(capexResults, outputDirectory)
    % WRITECAPEXRESULTSTOCSV Writes CAPEX sweep results to a timestamped CSV.
    %
    % Inputs:
    %   capexResults    - table of CAPEX sweep results.
    %   outputDirectory - directory where CSV should be written.
    %
    % Output:
    %   outputFilePath  - full path to written CSV file.

    arguments
        capexResults table
        outputDirectory {mustBeTextScalar} = "results"
    end

    validateCAPEXResultsTable(capexResults);

    if ~isfolder(outputDirectory)
        mkdir(outputDirectory);
    end

    timestamp = string(datetime("now", "Format", "yyyyMMdd_HHmmss"));
    outputFileName = "capex_sweep_results_" + timestamp + ".csv";
    outputFilePath = fullfile(outputDirectory, outputFileName);

    writetable(capexResults, outputFilePath);

    fprintf("Wrote %d CAPEX sweep rows to:\n%s\n", ...
        height(capexResults), outputFilePath);
end

function validateCAPEXResultsTable(capexResults)
    % VALIDATECAPEXRESULTSTABLE Enforces expected CAPEX output schema.

    requiredVariables = [ ...
        "capexScenarioName", ...
        "policyK", ...
        "policyE", ...
        "baselineServiceRate", ...
        "fixedInfrastructureCost", ...
        "serverCapitalCost", ...
        "serviceRateUpgradeCost", ...
        "serviceRateCurvature", ...
        "initialOutlay", ...
        "discountRate", ...
        "assetLifeYears", ...
        "capitalRecoveryFactor", ...
        "annualizedCapex"];

    actualVariables = string(capexResults.Properties.VariableNames);

    for iVar = 1:numel(requiredVariables)
        variableName = requiredVariables(iVar);
        assert(any(actualVariables == variableName), ...
            "validateCAPEXResultsTable:MissingVariable", ...
            "Missing required variable %s.", variableName);
    end

    assert(all(capexResults.policyK > 0), ...
        "validateCAPEXResultsTable:InvalidPolicyK", ...
        "policyK must be positive.");

    assert(all(mod(capexResults.policyK, 1) == 0), ...
        "validateCAPEXResultsTable:NonIntegerPolicyK", ...
        "policyK must contain integer server counts.");

    assert(all(capexResults.policyE > 0), ...
        "validateCAPEXResultsTable:InvalidPolicyE", ...
        "policyE must be positive.");

    assert(all(capexResults.discountRate >= 0), ...
        "validateCAPEXResultsTable:InvalidDiscountRate", ...
        "discountRate must be nonnegative.");

    assert(all(capexResults.assetLifeYears > 0), ...
        "validateCAPEXResultsTable:InvalidAssetLife", ...
        "assetLifeYears must be positive.");

    assert(all(capexResults.initialOutlay >= 0), ...
        "validateCAPEXResultsTable:InvalidInitialOutlay", ...
        "initialOutlay must be nonnegative.");

    assert(all(capexResults.capitalRecoveryFactor > 0), ...
        "validateCAPEXResultsTable:InvalidCRF", ...
        "capitalRecoveryFactor must be positive.");

    assert(all(capexResults.annualizedCapex >= 0), ...
        "validateCAPEXResultsTable:InvalidAnnualizedCapex", ...
        "annualizedCapex must be nonnegative.");

    expectedAnnualizedCapex = ...
        capexResults.initialOutlay .* capexResults.capitalRecoveryFactor;

    tolerance = 1e-8 * max(1, max(abs(expectedAnnualizedCapex)));

    assert(all(abs(capexResults.annualizedCapex - expectedAnnualizedCapex) <= tolerance), ...
        "validateCAPEXResultsTable:AnnualizedCapexMismatch", ...
        "annualizedCapex must equal initialOutlay .* capitalRecoveryFactor.");
end